# Generated by Django 3.1.2 on 2021-04-13 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovelBlog', '0003_auto_20210412_0139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_added']},
        ),
    ]
