# Generated by Django 3.1.2 on 2021-04-13 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NovelBlog', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
