# Generated by Django 3.1.2 on 2021-04-27 03:22

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('NovelBlog', '0008_auto_20210415_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
    ]
