# Generated by Django 3.1.2 on 2021-03-07 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0024_auto_20210222_1653'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Director',
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title', 'director']},
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='director',
        ),
    ]
