# Generated by Django 3.1.2 on 2021-03-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0026_auto_20210307_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='file',
            field=models.FileField(default=None, upload_to='movie-uploads/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
