# Generated by Django 3.1.2 on 2021-03-08 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0029_movie_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration',
        ),
    ]
