# Generated by Django 3.1.2 on 2021-03-08 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_remove_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dimensions',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='duration',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='fps',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
