# Generated by Django 3.1.2 on 2021-03-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0031_auto_20210307_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
