# Generated by Django 3.1.2 on 2021-03-08 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_movie_movie_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='director',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='director',
            name='last_name',
        ),
        migrations.AddField(
            model_name='director',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
