# Generated by Django 3.1.2 on 2021-03-08 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0033_auto_20210307_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_genre',
        ),
    ]
