# Generated by Django 3.1.2 on 2021-03-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0037_auto_20210308_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default=0, help_text='grabbed from imdb links', max_length=10, unique=True, verbose_name='imdb_id'),
            preserve_default=False,
        ),
    ]
