# Generated by Django 3.1.2 on 2021-03-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0047_auto_20210323_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='imdb',
            field=models.CharField(blank=True, help_text='grabbed from imdb links. for example, <a target="_blank" href="https://www.imdb.com/title/tt3322364/">Concussion</a> is 3322364', max_length=10, verbose_name='IMDB id'),
        ),
    ]
