# Generated by Django 3.1.2 on 2021-03-26 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0048_auto_20210323_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='found_articles',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
