# Generated by Django 3.1.2 on 2021-03-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0050_auto_20210326_0158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieInstance',
        ),
    ]
