# Generated by Django 3.1.2 on 2021-03-26 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0052_auto_20210326_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(blank=True, help_text='This field will be overwritten if given a valid IMDB id.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='found_articles',
            field=models.TextField(blank=True, help_text='HTML list output of found research articles on Google Scholar. Clear the text to find new articles.', max_length=5000, null=True, verbose_name='Found Research Articles'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(blank=True, help_text='This field will be overwritten if given a valid IMDB id.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(blank=True, help_text='For example, here is <a target="_blank" href="https://www.imdb.com/title/tt3322364/">Concussion\'s link</a>.', max_length=100, verbose_name='IMDB Link'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the movie. If left blank,                                                                                         the summary from a valid IMDB link will be used.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(blank=True, help_text='This field will be overwritten if given a valid IMDB id.', max_length=200, null=True),
        ),
    ]
