# Generated by Django 3.1.2 on 2021-03-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0053_auto_20210326_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='This field will be overwritten if given a valid IMDB id.', max_length=200),
        ),
    ]
