# Generated by Django 3.1.2 on 2021-03-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0055_auto_20210329_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='max_num_find_articles',
            field=models.IntegerField(default=5, help_text='Default number is 5.', verbose_name='Max number of research articles'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the movie. This field will                                                                                     be overwritten if given a valid IMDB id and left blank.', max_length=5000, null=True),
        ),
    ]
