# Generated by Django 3.1.2 on 2021-04-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_auto_20210408_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'free - access independent films and media outlets'), (2, 'low - access to Hollywood films'), (3, 'high - access to A-list movies')], verbose_name='Subscription Tier'),
        ),
    ]
