# Generated by Django 3.1.2 on 2021-04-14 03:51

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0066_auto_20210412_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='file',
            field=s3direct.fields.S3DirectField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_link',
            field=models.CharField(blank=True, help_text='For example, here is <a target="_blank" href="https://www.imdb.com/title/tt3322364/">Concussion\'s link</a>.', max_length=100, null=True, verbose_name='IMDB Link'),
        ),
    ]
