# Generated by Django 3.1.2 on 2021-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0068_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
