# Generated by Django 3.1.2 on 2021-04-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0072_auto_20210415_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'free - access independent films and media outlets'), (1, 'low - access to Hollywood films'), (2, 'premium - access to A-list movies')], default=0, verbose_name='Subscription Tier'),
        ),
    ]
