# Generated by Django 3.1.2 on 2021-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0075_auto_20210415_0330'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.CharField(blank=True, help_text='This field will be overwritten                                                                                                 if given a valid IMDB id and left blank.', max_length=100, null=True, verbose_name='Thumbnail'),
        ),
    ]
