# Generated by Django 3.1.2 on 2021-04-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0080_movie_ads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='ads',
            field=models.CharField(blank=True, help_text='For example, here is a <a target="_blank"\n        href="https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=">\n        Google VAMP example link</a>.', max_length=300, null=True, verbose_name='Google VAMP Ads Link'),
        ),
    ]
